# Generated by Django 2.0 on 2021-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20210211_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='mainphoto',
        ),
        migrations.AddField(
            model_name='review',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='review/userreviews/images'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='review/userreviews/images'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='review/userreviews/images'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='review/userreviews/images'),
        ),
    ]
