# Generated by Django 2.0 on 2021-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20210325_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='maxprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='minprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
