# Generated by Django 2.0 on 2021-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20210325_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
