# Generated by Django 2.0 on 2021-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_review_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='minprice',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
